project:
  version: @project.version@

spring:
  application:
    name: ticket-service
  main.banner-mode: "off"
  sql.init.mode: never
  
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${POSTGRES_DB}?currentSchema=${DB_SCHEMA:ticket},public
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: ${DB_SCHEMA:ticket}
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_schema: ${DB_SCHEMA:ticket}
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    schemas: ${DB_SCHEMA:ticket}
    default-schema: ${DB_SCHEMA:ticket}
    table: ${FLYWAY_TABLE:flyway_history_ticket}
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: true
    locations:
      - classpath:db/migration
      - classpath:db/r
    clean-disabled: true

external:
  event:
    url: ${EVENT_URL:http://event-dev:8080}


logging.level:
  org.springframework.jdbc.core: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  org.flywaydb.core.internal.command.DbMigrate: INFO

management:
  endpoints.web.exposure.include: "health,info"
  endpoint.health.show-details: always
