project:
  version: @project.version@

spring:
  application:
    name: event-service
  main.banner-mode: "off"
  sql.init.mode: never
  
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
      
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${POSTGRES_DB}?currentSchema=${DB_SCHEMA:events},public
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA:events}
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: ${DB_SCHEMA:events}
    properties:
      hibernate.default_schema: ${DB_SCHEMA:events}
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    schemas: ${DB_SCHEMA:events}
    default-schema: ${DB_SCHEMA:events}
    table: ${FLYWAY_TABLE:flyway_history_event}
    validate-on-migrate: true
    baseline-on-migrate: false
    locations:
      - classpath:db/migration
      - classpath:db/r
      - classpath:db/seeds
    clean-disabled: true

logging.level:
  org.springframework.jdbc.core: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints.web.exposure.include: "health,info"
  endpoint.health.show-details: always
