project:
  version: @project.version@

spring:
  application:
    name: notification-service
  main.banner-mode: "off"
  sql.init.mode: never

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${POSTGRES_DB}?currentSchema=${DB_SCHEMA:event},public
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA:event}
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: ${DB_SCHEMA:event}
    properties:
      hibernate.default_schema: ${DB_SCHEMA:event}
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    schemas: ${DB_SCHEMA:event}
    default-schema: ${DB_SCHEMA:event}
    table: ${FLYWAY_TABLE:flyway_history_event}
    validate-on-migrate: true
    baseline-on-migrate: false
    locations:
      - classpath:db/migration
      - classpath:db/r

  security:
    oauth2:
      resourceserver:

logging.level:
  root: INFO
  org.hibernate.SQL: WARN
  org.hibernate.type.descriptor.sql.BasicBinder: WARN

management:
  endpoints.web.exposure.include: "health,info"
  endpoint.health.show-details: never
